config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  resources :articles do
    resources :comments
  end

  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  has_many :comments, through: :article_comment

  validates :title, presence: true, length: { minimum: 3 }, uniqueness: true
  validates :text, presence: true, length: {minimum: 15}
  validates :category_id, presence: true
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  has_many :articles
  has_many :comments
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
  validates_presence_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :articles, through: :article_comment

  validates :message
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  def self.isAdmin?
    true #TODO: handle admin users later. Only the admin can create new articles
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.order("created_at DESC").limit(5).offset(0)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :text, :category_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/articles/index.html.erb
<h1>Welcome to rubyblog</h1>

<h4>
  <%= link_to 'Add article', 'articles/new' %>
</h4>

<br>

<table>
  <tr>
    <th>Entries</th>
  <tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create a new article in your blog</h1>

<% link_to '<-- Back', articles_path %>

<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :category_id %><br>
    <%= form.collection_select :category_id, Category.all, :id, :name, {} %>
  </p>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited, this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h2>
  Title: <%= @article.title %>
</h2>

<p>
  Content: <br>
  <%= @article.text %>
</p>

<p>
  Category: <br>
  <%= Category.find(@article.category_id).name %>
</p>

<h3> Comments </h3>

<%= Comment.all.where(@article.) %>

<%# TODO: Add user comments %>
<%# TODO: Add a form to enter comments %>

app/views/homepage/index.html.erb
<h1>Ruby blog</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>